# Generated by Django 6.0.4 on 2026-05-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('face', 'Eyewear'), ('neck', 'Neck & Jewellery'), ('chest', 'Tops & Shirts'), ('legs', 'Pants & Bottoms'), ('feet', 'Shoes & Footwear')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('kids', 'Kids'), ('unisex', 'Unisex')], max_length=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('overlay_png', models.ImageField(blank=True, null=True, upload_to='overlays/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('trend_score', models.IntegerField(default=0)),
                ('trend_label', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trend_score'],
            },
        ),
    ]
