# Generated by Django 6.0.4 on 2026-05-12 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(choices=[('casual', 'Casual'), ('party', 'Party'), ('wedding', 'Wedding'), ('gym', 'Gym'), ('office', 'Office'), ('all', 'All Occasions')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Outfit', max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('photo_url', models.CharField(max_length=500)),
                ('result_url', models.CharField(blank=True, max_length=500)),
                ('face_item', models.CharField(blank=True, max_length=200)),
                ('neck_item', models.CharField(blank=True, max_length=200)),
                ('chest_item', models.CharField(blank=True, max_length=200)),
                ('legs_item', models.CharField(blank=True, max_length=200)),
                ('feet_item', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
